package com.yxy.edu.model;

public class CtlParamKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CTL_PARAM.CTL_TYPE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String ctlType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CTL_PARAM.CTL_CODE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String ctlCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CTL_PARAM.CTL_TYPE
     *
     * @return the value of T_CTL_PARAM.CTL_TYPE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getCtlType() {
        return ctlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CTL_PARAM.CTL_TYPE
     *
     * @param ctlType the value for T_CTL_PARAM.CTL_TYPE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setCtlType(String ctlType) {
        this.ctlType = ctlType == null ? null : ctlType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CTL_PARAM.CTL_CODE
     *
     * @return the value of T_CTL_PARAM.CTL_CODE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getCtlCode() {
        return ctlCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CTL_PARAM.CTL_CODE
     *
     * @param ctlCode the value for T_CTL_PARAM.CTL_CODE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setCtlCode(String ctlCode) {
        this.ctlCode = ctlCode == null ? null : ctlCode.trim();
    }
}