package com.yxy.edu.model;

import java.util.Date;

public class CtlParam extends CtlParamKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CTL_PARAM.CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String ctlParam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CTL_PARAM.FLAG
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CTL_PARAM.REMARK
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CTL_PARAM.CREATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CTL_PARAM.UPDATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CTL_PARAM.CTL_PARAM
     *
     * @return the value of T_CTL_PARAM.CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getCtlParam() {
        return ctlParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CTL_PARAM.CTL_PARAM
     *
     * @param ctlParam the value for T_CTL_PARAM.CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setCtlParam(String ctlParam) {
        this.ctlParam = ctlParam == null ? null : ctlParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CTL_PARAM.FLAG
     *
     * @return the value of T_CTL_PARAM.FLAG
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CTL_PARAM.FLAG
     *
     * @param flag the value for T_CTL_PARAM.FLAG
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CTL_PARAM.REMARK
     *
     * @return the value of T_CTL_PARAM.REMARK
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CTL_PARAM.REMARK
     *
     * @param remark the value for T_CTL_PARAM.REMARK
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CTL_PARAM.CREATETIME
     *
     * @return the value of T_CTL_PARAM.CREATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CTL_PARAM.CREATETIME
     *
     * @param createtime the value for T_CTL_PARAM.CREATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CTL_PARAM.UPDATETIME
     *
     * @return the value of T_CTL_PARAM.UPDATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CTL_PARAM.UPDATETIME
     *
     * @param updatetime the value for T_CTL_PARAM.UPDATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}