package com.yxy.edu.model;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.ID
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.NAME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.PASSWORD
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.SEX
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.TEL
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.EMAIL
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.ADDRESS
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.STATUS
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.FILENAME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.REMARK
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.LEVELID
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private String levelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.SCOREOPERATION
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private Long scoreoperation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.CREATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.UPDATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.ID
     *
     * @return the value of T_MEMBER.ID
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.ID
     *
     * @param id the value for T_MEMBER.ID
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.NAME
     *
     * @return the value of T_MEMBER.NAME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.NAME
     *
     * @param name the value for T_MEMBER.NAME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.PASSWORD
     *
     * @return the value of T_MEMBER.PASSWORD
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.PASSWORD
     *
     * @param password the value for T_MEMBER.PASSWORD
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.SEX
     *
     * @return the value of T_MEMBER.SEX
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.SEX
     *
     * @param sex the value for T_MEMBER.SEX
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.TEL
     *
     * @return the value of T_MEMBER.TEL
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.TEL
     *
     * @param tel the value for T_MEMBER.TEL
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.EMAIL
     *
     * @return the value of T_MEMBER.EMAIL
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.EMAIL
     *
     * @param email the value for T_MEMBER.EMAIL
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.ADDRESS
     *
     * @return the value of T_MEMBER.ADDRESS
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.ADDRESS
     *
     * @param address the value for T_MEMBER.ADDRESS
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.STATUS
     *
     * @return the value of T_MEMBER.STATUS
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.STATUS
     *
     * @param status the value for T_MEMBER.STATUS
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.FILENAME
     *
     * @return the value of T_MEMBER.FILENAME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.FILENAME
     *
     * @param filename the value for T_MEMBER.FILENAME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.REMARK
     *
     * @return the value of T_MEMBER.REMARK
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.REMARK
     *
     * @param remark the value for T_MEMBER.REMARK
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.LEVELID
     *
     * @return the value of T_MEMBER.LEVELID
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public String getLevelid() {
        return levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.LEVELID
     *
     * @param levelid the value for T_MEMBER.LEVELID
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setLevelid(String levelid) {
        this.levelid = levelid == null ? null : levelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.SCOREOPERATION
     *
     * @return the value of T_MEMBER.SCOREOPERATION
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public Long getScoreoperation() {
        return scoreoperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.SCOREOPERATION
     *
     * @param scoreoperation the value for T_MEMBER.SCOREOPERATION
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setScoreoperation(Long scoreoperation) {
        this.scoreoperation = scoreoperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.CREATETIME
     *
     * @return the value of T_MEMBER.CREATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.CREATETIME
     *
     * @param createtime the value for T_MEMBER.CREATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.UPDATETIME
     *
     * @return the value of T_MEMBER.UPDATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.UPDATETIME
     *
     * @param updatetime the value for T_MEMBER.UPDATETIME
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}