package com.yxy.edu.model;

import java.util.Date;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.ID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.USERID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.REALNAME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.SEX
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.TEL
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.EMAIL
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.ADDRESS
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.FILENAME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.REMARK
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.LEVELID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private String levelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.SCOREOPERATION
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private Long scoreoperation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.CREATETIME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MEMBER.UPDATETIME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.ID
     *
     * @return the value of T_MEMBER.ID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.ID
     *
     * @param id the value for T_MEMBER.ID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.USERID
     *
     * @return the value of T_MEMBER.USERID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.USERID
     *
     * @param userid the value for T_MEMBER.USERID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.REALNAME
     *
     * @return the value of T_MEMBER.REALNAME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.REALNAME
     *
     * @param realname the value for T_MEMBER.REALNAME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.SEX
     *
     * @return the value of T_MEMBER.SEX
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.SEX
     *
     * @param sex the value for T_MEMBER.SEX
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.TEL
     *
     * @return the value of T_MEMBER.TEL
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.TEL
     *
     * @param tel the value for T_MEMBER.TEL
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.EMAIL
     *
     * @return the value of T_MEMBER.EMAIL
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.EMAIL
     *
     * @param email the value for T_MEMBER.EMAIL
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.ADDRESS
     *
     * @return the value of T_MEMBER.ADDRESS
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.ADDRESS
     *
     * @param address the value for T_MEMBER.ADDRESS
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.FILENAME
     *
     * @return the value of T_MEMBER.FILENAME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.FILENAME
     *
     * @param filename the value for T_MEMBER.FILENAME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.REMARK
     *
     * @return the value of T_MEMBER.REMARK
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.REMARK
     *
     * @param remark the value for T_MEMBER.REMARK
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.LEVELID
     *
     * @return the value of T_MEMBER.LEVELID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public String getLevelid() {
        return levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.LEVELID
     *
     * @param levelid the value for T_MEMBER.LEVELID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setLevelid(String levelid) {
        this.levelid = levelid == null ? null : levelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.SCOREOPERATION
     *
     * @return the value of T_MEMBER.SCOREOPERATION
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public Long getScoreoperation() {
        return scoreoperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.SCOREOPERATION
     *
     * @param scoreoperation the value for T_MEMBER.SCOREOPERATION
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setScoreoperation(Long scoreoperation) {
        this.scoreoperation = scoreoperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.CREATETIME
     *
     * @return the value of T_MEMBER.CREATETIME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.CREATETIME
     *
     * @param createtime the value for T_MEMBER.CREATETIME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MEMBER.UPDATETIME
     *
     * @return the value of T_MEMBER.UPDATETIME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MEMBER.UPDATETIME
     *
     * @param updatetime the value for T_MEMBER.UPDATETIME
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}