package com.yxy.edu.model;

import java.util.Date;

public class ProductCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_CATEGORY.ID
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_CATEGORY.PARENTID
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private Long parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_CATEGORY.CATEGORYNAME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private String categoryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_CATEGORY.REMARK
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_CATEGORY.CREATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_CATEGORY.UPDATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_CATEGORY.ID
     *
     * @return the value of T_PRODUCT_CATEGORY.ID
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_CATEGORY.ID
     *
     * @param id the value for T_PRODUCT_CATEGORY.ID
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_CATEGORY.PARENTID
     *
     * @return the value of T_PRODUCT_CATEGORY.PARENTID
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public Long getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_CATEGORY.PARENTID
     *
     * @param parentid the value for T_PRODUCT_CATEGORY.PARENTID
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setParentid(Long parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_CATEGORY.CATEGORYNAME
     *
     * @return the value of T_PRODUCT_CATEGORY.CATEGORYNAME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_CATEGORY.CATEGORYNAME
     *
     * @param categoryname the value for T_PRODUCT_CATEGORY.CATEGORYNAME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname == null ? null : categoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_CATEGORY.REMARK
     *
     * @return the value of T_PRODUCT_CATEGORY.REMARK
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_CATEGORY.REMARK
     *
     * @param remark the value for T_PRODUCT_CATEGORY.REMARK
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_CATEGORY.CREATETIME
     *
     * @return the value of T_PRODUCT_CATEGORY.CREATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_CATEGORY.CREATETIME
     *
     * @param createtime the value for T_PRODUCT_CATEGORY.CREATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_CATEGORY.UPDATETIME
     *
     * @return the value of T_PRODUCT_CATEGORY.UPDATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_CATEGORY.UPDATETIME
     *
     * @param updatetime the value for T_PRODUCT_CATEGORY.UPDATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}