package com.yxy.edu.model;

import java.util.Date;

public class ProductBrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_BRAND.ID
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_BRAND.BRANDNAME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private String brandname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_BRAND.LOGONAME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private String logoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_BRAND.PLACE
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_BRAND.REMARK
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_BRAND.CREATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_PRODUCT_BRAND.UPDATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_BRAND.ID
     *
     * @return the value of T_PRODUCT_BRAND.ID
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_BRAND.ID
     *
     * @param id the value for T_PRODUCT_BRAND.ID
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_BRAND.BRANDNAME
     *
     * @return the value of T_PRODUCT_BRAND.BRANDNAME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public String getBrandname() {
        return brandname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_BRAND.BRANDNAME
     *
     * @param brandname the value for T_PRODUCT_BRAND.BRANDNAME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setBrandname(String brandname) {
        this.brandname = brandname == null ? null : brandname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_BRAND.LOGONAME
     *
     * @return the value of T_PRODUCT_BRAND.LOGONAME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public String getLogoname() {
        return logoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_BRAND.LOGONAME
     *
     * @param logoname the value for T_PRODUCT_BRAND.LOGONAME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setLogoname(String logoname) {
        this.logoname = logoname == null ? null : logoname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_BRAND.PLACE
     *
     * @return the value of T_PRODUCT_BRAND.PLACE
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_BRAND.PLACE
     *
     * @param place the value for T_PRODUCT_BRAND.PLACE
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_BRAND.REMARK
     *
     * @return the value of T_PRODUCT_BRAND.REMARK
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_BRAND.REMARK
     *
     * @param remark the value for T_PRODUCT_BRAND.REMARK
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_BRAND.CREATETIME
     *
     * @return the value of T_PRODUCT_BRAND.CREATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_BRAND.CREATETIME
     *
     * @param createtime the value for T_PRODUCT_BRAND.CREATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_PRODUCT_BRAND.UPDATETIME
     *
     * @return the value of T_PRODUCT_BRAND.UPDATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_PRODUCT_BRAND.UPDATETIME
     *
     * @param updatetime the value for T_PRODUCT_BRAND.UPDATETIME
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}