package com.yxy.edu.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNull() {
            addCriterion("PRODUCTNAME is null");
            return (Criteria) this;
        }

        public Criteria andProductnameIsNotNull() {
            addCriterion("PRODUCTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andProductnameEqualTo(String value) {
            addCriterion("PRODUCTNAME =", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotEqualTo(String value) {
            addCriterion("PRODUCTNAME <>", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThan(String value) {
            addCriterion("PRODUCTNAME >", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCTNAME >=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThan(String value) {
            addCriterion("PRODUCTNAME <", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLessThanOrEqualTo(String value) {
            addCriterion("PRODUCTNAME <=", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameLike(String value) {
            addCriterion("PRODUCTNAME like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotLike(String value) {
            addCriterion("PRODUCTNAME not like", value, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameIn(List<String> values) {
            addCriterion("PRODUCTNAME in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotIn(List<String> values) {
            addCriterion("PRODUCTNAME not in", values, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameBetween(String value1, String value2) {
            addCriterion("PRODUCTNAME between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andProductnameNotBetween(String value1, String value2) {
            addCriterion("PRODUCTNAME not between", value1, value2, "productname");
            return (Criteria) this;
        }

        public Criteria andBrandidIsNull() {
            addCriterion("BRANDID is null");
            return (Criteria) this;
        }

        public Criteria andBrandidIsNotNull() {
            addCriterion("BRANDID is not null");
            return (Criteria) this;
        }

        public Criteria andBrandidEqualTo(String value) {
            addCriterion("BRANDID =", value, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidNotEqualTo(String value) {
            addCriterion("BRANDID <>", value, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidGreaterThan(String value) {
            addCriterion("BRANDID >", value, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidGreaterThanOrEqualTo(String value) {
            addCriterion("BRANDID >=", value, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidLessThan(String value) {
            addCriterion("BRANDID <", value, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidLessThanOrEqualTo(String value) {
            addCriterion("BRANDID <=", value, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidLike(String value) {
            addCriterion("BRANDID like", value, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidNotLike(String value) {
            addCriterion("BRANDID not like", value, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidIn(List<String> values) {
            addCriterion("BRANDID in", values, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidNotIn(List<String> values) {
            addCriterion("BRANDID not in", values, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidBetween(String value1, String value2) {
            addCriterion("BRANDID between", value1, value2, "brandid");
            return (Criteria) this;
        }

        public Criteria andBrandidNotBetween(String value1, String value2) {
            addCriterion("BRANDID not between", value1, value2, "brandid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidIsNull() {
            addCriterion("CATAGORYID is null");
            return (Criteria) this;
        }

        public Criteria andCatagoryidIsNotNull() {
            addCriterion("CATAGORYID is not null");
            return (Criteria) this;
        }

        public Criteria andCatagoryidEqualTo(String value) {
            addCriterion("CATAGORYID =", value, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidNotEqualTo(String value) {
            addCriterion("CATAGORYID <>", value, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidGreaterThan(String value) {
            addCriterion("CATAGORYID >", value, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidGreaterThanOrEqualTo(String value) {
            addCriterion("CATAGORYID >=", value, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidLessThan(String value) {
            addCriterion("CATAGORYID <", value, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidLessThanOrEqualTo(String value) {
            addCriterion("CATAGORYID <=", value, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidLike(String value) {
            addCriterion("CATAGORYID like", value, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidNotLike(String value) {
            addCriterion("CATAGORYID not like", value, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidIn(List<String> values) {
            addCriterion("CATAGORYID in", values, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidNotIn(List<String> values) {
            addCriterion("CATAGORYID not in", values, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidBetween(String value1, String value2) {
            addCriterion("CATAGORYID between", value1, value2, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andCatagoryidNotBetween(String value1, String value2) {
            addCriterion("CATAGORYID not between", value1, value2, "catagoryid");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("PRIORITY is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("PRIORITY is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(String value) {
            addCriterion("PRIORITY =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(String value) {
            addCriterion("PRIORITY <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(String value) {
            addCriterion("PRIORITY >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(String value) {
            addCriterion("PRIORITY >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(String value) {
            addCriterion("PRIORITY <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(String value) {
            addCriterion("PRIORITY <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLike(String value) {
            addCriterion("PRIORITY like", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotLike(String value) {
            addCriterion("PRIORITY not like", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<String> values) {
            addCriterion("PRIORITY in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<String> values) {
            addCriterion("PRIORITY not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(String value1, String value2) {
            addCriterion("PRIORITY between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(String value1, String value2) {
            addCriterion("PRIORITY not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andStadardIsNull() {
            addCriterion("STADARD is null");
            return (Criteria) this;
        }

        public Criteria andStadardIsNotNull() {
            addCriterion("STADARD is not null");
            return (Criteria) this;
        }

        public Criteria andStadardEqualTo(Long value) {
            addCriterion("STADARD =", value, "stadard");
            return (Criteria) this;
        }

        public Criteria andStadardNotEqualTo(Long value) {
            addCriterion("STADARD <>", value, "stadard");
            return (Criteria) this;
        }

        public Criteria andStadardGreaterThan(Long value) {
            addCriterion("STADARD >", value, "stadard");
            return (Criteria) this;
        }

        public Criteria andStadardGreaterThanOrEqualTo(Long value) {
            addCriterion("STADARD >=", value, "stadard");
            return (Criteria) this;
        }

        public Criteria andStadardLessThan(Long value) {
            addCriterion("STADARD <", value, "stadard");
            return (Criteria) this;
        }

        public Criteria andStadardLessThanOrEqualTo(Long value) {
            addCriterion("STADARD <=", value, "stadard");
            return (Criteria) this;
        }

        public Criteria andStadardIn(List<Long> values) {
            addCriterion("STADARD in", values, "stadard");
            return (Criteria) this;
        }

        public Criteria andStadardNotIn(List<Long> values) {
            addCriterion("STADARD not in", values, "stadard");
            return (Criteria) this;
        }

        public Criteria andStadardBetween(Long value1, Long value2) {
            addCriterion("STADARD between", value1, value2, "stadard");
            return (Criteria) this;
        }

        public Criteria andStadardNotBetween(Long value1, Long value2) {
            addCriterion("STADARD not between", value1, value2, "stadard");
            return (Criteria) this;
        }

        public Criteria andPlaceIsNull() {
            addCriterion("PLACE is null");
            return (Criteria) this;
        }

        public Criteria andPlaceIsNotNull() {
            addCriterion("PLACE is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceEqualTo(String value) {
            addCriterion("PLACE =", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceNotEqualTo(String value) {
            addCriterion("PLACE <>", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceGreaterThan(String value) {
            addCriterion("PLACE >", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceGreaterThanOrEqualTo(String value) {
            addCriterion("PLACE >=", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceLessThan(String value) {
            addCriterion("PLACE <", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceLessThanOrEqualTo(String value) {
            addCriterion("PLACE <=", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceLike(String value) {
            addCriterion("PLACE like", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceNotLike(String value) {
            addCriterion("PLACE not like", value, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceIn(List<String> values) {
            addCriterion("PLACE in", values, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceNotIn(List<String> values) {
            addCriterion("PLACE not in", values, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceBetween(String value1, String value2) {
            addCriterion("PLACE between", value1, value2, "place");
            return (Criteria) this;
        }

        public Criteria andPlaceNotBetween(String value1, String value2) {
            addCriterion("PLACE not between", value1, value2, "place");
            return (Criteria) this;
        }

        public Criteria andTextureIsNull() {
            addCriterion("TEXTURE is null");
            return (Criteria) this;
        }

        public Criteria andTextureIsNotNull() {
            addCriterion("TEXTURE is not null");
            return (Criteria) this;
        }

        public Criteria andTextureEqualTo(String value) {
            addCriterion("TEXTURE =", value, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureNotEqualTo(String value) {
            addCriterion("TEXTURE <>", value, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureGreaterThan(String value) {
            addCriterion("TEXTURE >", value, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureGreaterThanOrEqualTo(String value) {
            addCriterion("TEXTURE >=", value, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureLessThan(String value) {
            addCriterion("TEXTURE <", value, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureLessThanOrEqualTo(String value) {
            addCriterion("TEXTURE <=", value, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureLike(String value) {
            addCriterion("TEXTURE like", value, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureNotLike(String value) {
            addCriterion("TEXTURE not like", value, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureIn(List<String> values) {
            addCriterion("TEXTURE in", values, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureNotIn(List<String> values) {
            addCriterion("TEXTURE not in", values, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureBetween(String value1, String value2) {
            addCriterion("TEXTURE between", value1, value2, "texture");
            return (Criteria) this;
        }

        public Criteria andTextureNotBetween(String value1, String value2) {
            addCriterion("TEXTURE not between", value1, value2, "texture");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("UNIT is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("UNIT is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("UNIT =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("UNIT <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("UNIT >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("UNIT >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("UNIT <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("UNIT <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("UNIT like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("UNIT not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("UNIT in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("UNIT not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("UNIT between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("UNIT not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Long value) {
            addCriterion("WEIGHT =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Long value) {
            addCriterion("WEIGHT <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Long value) {
            addCriterion("WEIGHT >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Long value) {
            addCriterion("WEIGHT >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Long value) {
            addCriterion("WEIGHT <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Long value) {
            addCriterion("WEIGHT <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Long> values) {
            addCriterion("WEIGHT in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Long> values) {
            addCriterion("WEIGHT not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Long value1, Long value2) {
            addCriterion("WEIGHT between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Long value1, Long value2) {
            addCriterion("WEIGHT not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andShowpriceIsNull() {
            addCriterion("SHOWPRICE is null");
            return (Criteria) this;
        }

        public Criteria andShowpriceIsNotNull() {
            addCriterion("SHOWPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andShowpriceEqualTo(Long value) {
            addCriterion("SHOWPRICE =", value, "showprice");
            return (Criteria) this;
        }

        public Criteria andShowpriceNotEqualTo(Long value) {
            addCriterion("SHOWPRICE <>", value, "showprice");
            return (Criteria) this;
        }

        public Criteria andShowpriceGreaterThan(Long value) {
            addCriterion("SHOWPRICE >", value, "showprice");
            return (Criteria) this;
        }

        public Criteria andShowpriceGreaterThanOrEqualTo(Long value) {
            addCriterion("SHOWPRICE >=", value, "showprice");
            return (Criteria) this;
        }

        public Criteria andShowpriceLessThan(Long value) {
            addCriterion("SHOWPRICE <", value, "showprice");
            return (Criteria) this;
        }

        public Criteria andShowpriceLessThanOrEqualTo(Long value) {
            addCriterion("SHOWPRICE <=", value, "showprice");
            return (Criteria) this;
        }

        public Criteria andShowpriceIn(List<Long> values) {
            addCriterion("SHOWPRICE in", values, "showprice");
            return (Criteria) this;
        }

        public Criteria andShowpriceNotIn(List<Long> values) {
            addCriterion("SHOWPRICE not in", values, "showprice");
            return (Criteria) this;
        }

        public Criteria andShowpriceBetween(Long value1, Long value2) {
            addCriterion("SHOWPRICE between", value1, value2, "showprice");
            return (Criteria) this;
        }

        public Criteria andShowpriceNotBetween(Long value1, Long value2) {
            addCriterion("SHOWPRICE not between", value1, value2, "showprice");
            return (Criteria) this;
        }

        public Criteria andMarketpriceIsNull() {
            addCriterion("MARKETPRICE is null");
            return (Criteria) this;
        }

        public Criteria andMarketpriceIsNotNull() {
            addCriterion("MARKETPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andMarketpriceEqualTo(Long value) {
            addCriterion("MARKETPRICE =", value, "marketprice");
            return (Criteria) this;
        }

        public Criteria andMarketpriceNotEqualTo(Long value) {
            addCriterion("MARKETPRICE <>", value, "marketprice");
            return (Criteria) this;
        }

        public Criteria andMarketpriceGreaterThan(Long value) {
            addCriterion("MARKETPRICE >", value, "marketprice");
            return (Criteria) this;
        }

        public Criteria andMarketpriceGreaterThanOrEqualTo(Long value) {
            addCriterion("MARKETPRICE >=", value, "marketprice");
            return (Criteria) this;
        }

        public Criteria andMarketpriceLessThan(Long value) {
            addCriterion("MARKETPRICE <", value, "marketprice");
            return (Criteria) this;
        }

        public Criteria andMarketpriceLessThanOrEqualTo(Long value) {
            addCriterion("MARKETPRICE <=", value, "marketprice");
            return (Criteria) this;
        }

        public Criteria andMarketpriceIn(List<Long> values) {
            addCriterion("MARKETPRICE in", values, "marketprice");
            return (Criteria) this;
        }

        public Criteria andMarketpriceNotIn(List<Long> values) {
            addCriterion("MARKETPRICE not in", values, "marketprice");
            return (Criteria) this;
        }

        public Criteria andMarketpriceBetween(Long value1, Long value2) {
            addCriterion("MARKETPRICE between", value1, value2, "marketprice");
            return (Criteria) this;
        }

        public Criteria andMarketpriceNotBetween(Long value1, Long value2) {
            addCriterion("MARKETPRICE not between", value1, value2, "marketprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceIsNull() {
            addCriterion("COSTPRICE is null");
            return (Criteria) this;
        }

        public Criteria andCostpriceIsNotNull() {
            addCriterion("COSTPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andCostpriceEqualTo(Long value) {
            addCriterion("COSTPRICE =", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotEqualTo(Long value) {
            addCriterion("COSTPRICE <>", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceGreaterThan(Long value) {
            addCriterion("COSTPRICE >", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceGreaterThanOrEqualTo(Long value) {
            addCriterion("COSTPRICE >=", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceLessThan(Long value) {
            addCriterion("COSTPRICE <", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceLessThanOrEqualTo(Long value) {
            addCriterion("COSTPRICE <=", value, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceIn(List<Long> values) {
            addCriterion("COSTPRICE in", values, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotIn(List<Long> values) {
            addCriterion("COSTPRICE not in", values, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceBetween(Long value1, Long value2) {
            addCriterion("COSTPRICE between", value1, value2, "costprice");
            return (Criteria) this;
        }

        public Criteria andCostpriceNotBetween(Long value1, Long value2) {
            addCriterion("COSTPRICE not between", value1, value2, "costprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceIsNull() {
            addCriterion("MINPRICE is null");
            return (Criteria) this;
        }

        public Criteria andMinpriceIsNotNull() {
            addCriterion("MINPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andMinpriceEqualTo(Long value) {
            addCriterion("MINPRICE =", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceNotEqualTo(Long value) {
            addCriterion("MINPRICE <>", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceGreaterThan(Long value) {
            addCriterion("MINPRICE >", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceGreaterThanOrEqualTo(Long value) {
            addCriterion("MINPRICE >=", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceLessThan(Long value) {
            addCriterion("MINPRICE <", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceLessThanOrEqualTo(Long value) {
            addCriterion("MINPRICE <=", value, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceIn(List<Long> values) {
            addCriterion("MINPRICE in", values, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceNotIn(List<Long> values) {
            addCriterion("MINPRICE not in", values, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceBetween(Long value1, Long value2) {
            addCriterion("MINPRICE between", value1, value2, "minprice");
            return (Criteria) this;
        }

        public Criteria andMinpriceNotBetween(Long value1, Long value2) {
            addCriterion("MINPRICE not between", value1, value2, "minprice");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeIsNull() {
            addCriterion("SELLSTARTTIME is null");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeIsNotNull() {
            addCriterion("SELLSTARTTIME is not null");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeEqualTo(Date value) {
            addCriterion("SELLSTARTTIME =", value, "sellstarttime");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeNotEqualTo(Date value) {
            addCriterion("SELLSTARTTIME <>", value, "sellstarttime");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeGreaterThan(Date value) {
            addCriterion("SELLSTARTTIME >", value, "sellstarttime");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SELLSTARTTIME >=", value, "sellstarttime");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeLessThan(Date value) {
            addCriterion("SELLSTARTTIME <", value, "sellstarttime");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeLessThanOrEqualTo(Date value) {
            addCriterion("SELLSTARTTIME <=", value, "sellstarttime");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeIn(List<Date> values) {
            addCriterion("SELLSTARTTIME in", values, "sellstarttime");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeNotIn(List<Date> values) {
            addCriterion("SELLSTARTTIME not in", values, "sellstarttime");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeBetween(Date value1, Date value2) {
            addCriterion("SELLSTARTTIME between", value1, value2, "sellstarttime");
            return (Criteria) this;
        }

        public Criteria andSellstarttimeNotBetween(Date value1, Date value2) {
            addCriterion("SELLSTARTTIME not between", value1, value2, "sellstarttime");
            return (Criteria) this;
        }

        public Criteria andSellendtimeIsNull() {
            addCriterion("SELLENDTIME is null");
            return (Criteria) this;
        }

        public Criteria andSellendtimeIsNotNull() {
            addCriterion("SELLENDTIME is not null");
            return (Criteria) this;
        }

        public Criteria andSellendtimeEqualTo(Date value) {
            addCriterion("SELLENDTIME =", value, "sellendtime");
            return (Criteria) this;
        }

        public Criteria andSellendtimeNotEqualTo(Date value) {
            addCriterion("SELLENDTIME <>", value, "sellendtime");
            return (Criteria) this;
        }

        public Criteria andSellendtimeGreaterThan(Date value) {
            addCriterion("SELLENDTIME >", value, "sellendtime");
            return (Criteria) this;
        }

        public Criteria andSellendtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SELLENDTIME >=", value, "sellendtime");
            return (Criteria) this;
        }

        public Criteria andSellendtimeLessThan(Date value) {
            addCriterion("SELLENDTIME <", value, "sellendtime");
            return (Criteria) this;
        }

        public Criteria andSellendtimeLessThanOrEqualTo(Date value) {
            addCriterion("SELLENDTIME <=", value, "sellendtime");
            return (Criteria) this;
        }

        public Criteria andSellendtimeIn(List<Date> values) {
            addCriterion("SELLENDTIME in", values, "sellendtime");
            return (Criteria) this;
        }

        public Criteria andSellendtimeNotIn(List<Date> values) {
            addCriterion("SELLENDTIME not in", values, "sellendtime");
            return (Criteria) this;
        }

        public Criteria andSellendtimeBetween(Date value1, Date value2) {
            addCriterion("SELLENDTIME between", value1, value2, "sellendtime");
            return (Criteria) this;
        }

        public Criteria andSellendtimeNotBetween(Date value1, Date value2) {
            addCriterion("SELLENDTIME not between", value1, value2, "sellendtime");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("KEYWORD is null");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("KEYWORD is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("KEYWORD =", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("KEYWORD <>", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("KEYWORD >", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("KEYWORD >=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("KEYWORD <", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("KEYWORD <=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("KEYWORD like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("KEYWORD not like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordIn(List<String> values) {
            addCriterion("KEYWORD in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotIn(List<String> values) {
            addCriterion("KEYWORD not in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("KEYWORD between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("KEYWORD not between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameIsNull() {
            addCriterion("THUMBNAILNAME is null");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameIsNotNull() {
            addCriterion("THUMBNAILNAME is not null");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameEqualTo(String value) {
            addCriterion("THUMBNAILNAME =", value, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameNotEqualTo(String value) {
            addCriterion("THUMBNAILNAME <>", value, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameGreaterThan(String value) {
            addCriterion("THUMBNAILNAME >", value, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameGreaterThanOrEqualTo(String value) {
            addCriterion("THUMBNAILNAME >=", value, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameLessThan(String value) {
            addCriterion("THUMBNAILNAME <", value, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameLessThanOrEqualTo(String value) {
            addCriterion("THUMBNAILNAME <=", value, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameLike(String value) {
            addCriterion("THUMBNAILNAME like", value, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameNotLike(String value) {
            addCriterion("THUMBNAILNAME not like", value, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameIn(List<String> values) {
            addCriterion("THUMBNAILNAME in", values, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameNotIn(List<String> values) {
            addCriterion("THUMBNAILNAME not in", values, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameBetween(String value1, String value2) {
            addCriterion("THUMBNAILNAME between", value1, value2, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andThumbnailnameNotBetween(String value1, String value2) {
            addCriterion("THUMBNAILNAME not between", value1, value2, "thumbnailname");
            return (Criteria) this;
        }

        public Criteria andPicturenameIsNull() {
            addCriterion("PICTURENAME is null");
            return (Criteria) this;
        }

        public Criteria andPicturenameIsNotNull() {
            addCriterion("PICTURENAME is not null");
            return (Criteria) this;
        }

        public Criteria andPicturenameEqualTo(String value) {
            addCriterion("PICTURENAME =", value, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameNotEqualTo(String value) {
            addCriterion("PICTURENAME <>", value, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameGreaterThan(String value) {
            addCriterion("PICTURENAME >", value, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameGreaterThanOrEqualTo(String value) {
            addCriterion("PICTURENAME >=", value, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameLessThan(String value) {
            addCriterion("PICTURENAME <", value, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameLessThanOrEqualTo(String value) {
            addCriterion("PICTURENAME <=", value, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameLike(String value) {
            addCriterion("PICTURENAME like", value, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameNotLike(String value) {
            addCriterion("PICTURENAME not like", value, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameIn(List<String> values) {
            addCriterion("PICTURENAME in", values, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameNotIn(List<String> values) {
            addCriterion("PICTURENAME not in", values, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameBetween(String value1, String value2) {
            addCriterion("PICTURENAME between", value1, value2, "picturename");
            return (Criteria) this;
        }

        public Criteria andPicturenameNotBetween(String value1, String value2) {
            addCriterion("PICTURENAME not between", value1, value2, "picturename");
            return (Criteria) this;
        }

        public Criteria andTotalquantityIsNull() {
            addCriterion("TOTALQUANTITY is null");
            return (Criteria) this;
        }

        public Criteria andTotalquantityIsNotNull() {
            addCriterion("TOTALQUANTITY is not null");
            return (Criteria) this;
        }

        public Criteria andTotalquantityEqualTo(Long value) {
            addCriterion("TOTALQUANTITY =", value, "totalquantity");
            return (Criteria) this;
        }

        public Criteria andTotalquantityNotEqualTo(Long value) {
            addCriterion("TOTALQUANTITY <>", value, "totalquantity");
            return (Criteria) this;
        }

        public Criteria andTotalquantityGreaterThan(Long value) {
            addCriterion("TOTALQUANTITY >", value, "totalquantity");
            return (Criteria) this;
        }

        public Criteria andTotalquantityGreaterThanOrEqualTo(Long value) {
            addCriterion("TOTALQUANTITY >=", value, "totalquantity");
            return (Criteria) this;
        }

        public Criteria andTotalquantityLessThan(Long value) {
            addCriterion("TOTALQUANTITY <", value, "totalquantity");
            return (Criteria) this;
        }

        public Criteria andTotalquantityLessThanOrEqualTo(Long value) {
            addCriterion("TOTALQUANTITY <=", value, "totalquantity");
            return (Criteria) this;
        }

        public Criteria andTotalquantityIn(List<Long> values) {
            addCriterion("TOTALQUANTITY in", values, "totalquantity");
            return (Criteria) this;
        }

        public Criteria andTotalquantityNotIn(List<Long> values) {
            addCriterion("TOTALQUANTITY not in", values, "totalquantity");
            return (Criteria) this;
        }

        public Criteria andTotalquantityBetween(Long value1, Long value2) {
            addCriterion("TOTALQUANTITY between", value1, value2, "totalquantity");
            return (Criteria) this;
        }

        public Criteria andTotalquantityNotBetween(Long value1, Long value2) {
            addCriterion("TOTALQUANTITY not between", value1, value2, "totalquantity");
            return (Criteria) this;
        }

        public Criteria andSalequantityIsNull() {
            addCriterion("SALEQUANTITY is null");
            return (Criteria) this;
        }

        public Criteria andSalequantityIsNotNull() {
            addCriterion("SALEQUANTITY is not null");
            return (Criteria) this;
        }

        public Criteria andSalequantityEqualTo(Long value) {
            addCriterion("SALEQUANTITY =", value, "salequantity");
            return (Criteria) this;
        }

        public Criteria andSalequantityNotEqualTo(Long value) {
            addCriterion("SALEQUANTITY <>", value, "salequantity");
            return (Criteria) this;
        }

        public Criteria andSalequantityGreaterThan(Long value) {
            addCriterion("SALEQUANTITY >", value, "salequantity");
            return (Criteria) this;
        }

        public Criteria andSalequantityGreaterThanOrEqualTo(Long value) {
            addCriterion("SALEQUANTITY >=", value, "salequantity");
            return (Criteria) this;
        }

        public Criteria andSalequantityLessThan(Long value) {
            addCriterion("SALEQUANTITY <", value, "salequantity");
            return (Criteria) this;
        }

        public Criteria andSalequantityLessThanOrEqualTo(Long value) {
            addCriterion("SALEQUANTITY <=", value, "salequantity");
            return (Criteria) this;
        }

        public Criteria andSalequantityIn(List<Long> values) {
            addCriterion("SALEQUANTITY in", values, "salequantity");
            return (Criteria) this;
        }

        public Criteria andSalequantityNotIn(List<Long> values) {
            addCriterion("SALEQUANTITY not in", values, "salequantity");
            return (Criteria) this;
        }

        public Criteria andSalequantityBetween(Long value1, Long value2) {
            addCriterion("SALEQUANTITY between", value1, value2, "salequantity");
            return (Criteria) this;
        }

        public Criteria andSalequantityNotBetween(Long value1, Long value2) {
            addCriterion("SALEQUANTITY not between", value1, value2, "salequantity");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CREATETIME is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CREATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CREATETIME =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CREATETIME <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CREATETIME >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATETIME >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CREATETIME <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATETIME <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CREATETIME in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CREATETIME not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CREATETIME between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATETIME not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("UPDATETIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("UPDATETIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("UPDATETIME =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("UPDATETIME <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("UPDATETIME >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("UPDATETIME <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATETIME <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("UPDATETIME in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("UPDATETIME not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATETIME not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_PRODUCT
     *
     * @mbggenerated do_not_delete_during_merge Fri May 17 19:13:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_PRODUCT
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}