package com.yxy.edu.model;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.ID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.USERCODE
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.PASSWORD
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.STATUS
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.ROLE
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.CREATETIME
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.UPDATETIME
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.ID
     *
     * @return the value of T_USER.ID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.ID
     *
     * @param id the value for T_USER.ID
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.USERCODE
     *
     * @return the value of T_USER.USERCODE
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.USERCODE
     *
     * @param usercode the value for T_USER.USERCODE
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode == null ? null : usercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.PASSWORD
     *
     * @return the value of T_USER.PASSWORD
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.PASSWORD
     *
     * @param password the value for T_USER.PASSWORD
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.STATUS
     *
     * @return the value of T_USER.STATUS
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.STATUS
     *
     * @param status the value for T_USER.STATUS
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.ROLE
     *
     * @return the value of T_USER.ROLE
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.ROLE
     *
     * @param role the value for T_USER.ROLE
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.CREATETIME
     *
     * @return the value of T_USER.CREATETIME
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.CREATETIME
     *
     * @param createtime the value for T_USER.CREATETIME
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.UPDATETIME
     *
     * @return the value of T_USER.UPDATETIME
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.UPDATETIME
     *
     * @param updatetime the value for T_USER.UPDATETIME
     *
     * @mbggenerated Tue May 21 18:54:49 CST 2019
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}