package com.yxy.edu.mapper;

import com.yxy.edu.model.CtlParam;
import com.yxy.edu.model.CtlParamExample;
import com.yxy.edu.model.CtlParamKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtlParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int countByExample(CtlParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int deleteByExample(CtlParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int deleteByPrimaryKey(CtlParamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int insert(CtlParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int insertSelective(CtlParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    List<CtlParam> selectByExample(CtlParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    CtlParam selectByPrimaryKey(CtlParamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") CtlParam record, @Param("example") CtlParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int updateByExample(@Param("record") CtlParam record, @Param("example") CtlParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int updateByPrimaryKeySelective(CtlParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_CTL_PARAM
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int updateByPrimaryKey(CtlParam record);

    List<CtlParam> selectByType(String ctlType);
}