package com.yxy.edu.mapper;

import com.yxy.edu.model.Member;
import com.yxy.edu.model.MemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    int countByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    int deleteByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    int insert(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    int insertSelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    List<Member> selectByExample(MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    Member selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    int updateByPrimaryKeySelective(Member record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER
     *
     * @mbggenerated Tue May 21 18:54:48 CST 2019
     */
    int updateByPrimaryKey(Member record);
}