package com.yxy.edu.mapper;

import com.yxy.edu.model.MemberShare;
import com.yxy.edu.model.MemberShareExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemberShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int countByExample(MemberShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int deleteByExample(MemberShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int insert(MemberShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int insertSelective(MemberShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    List<MemberShare> selectByExample(MemberShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    MemberShare selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") MemberShare record, @Param("example") MemberShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int updateByExample(@Param("record") MemberShare record, @Param("example") MemberShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int updateByPrimaryKeySelective(MemberShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_MEMBER_SHARE
     *
     * @mbggenerated Thu May 16 18:53:42 CST 2019
     */
    int updateByPrimaryKey(MemberShare record);
}