package com.yxy.edu.mapper;

import com.yxy.edu.model.ProductCategory;
import com.yxy.edu.model.ProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    int countByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    int deleteByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    int insert(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    int insertSelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    List<ProductCategory> selectByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    ProductCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    int updateByExample(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    int updateByPrimaryKeySelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_PRODUCT_CATEGORY
     *
     * @mbggenerated Fri May 17 19:13:45 CST 2019
     */
    int updateByPrimaryKey(ProductCategory record);
}